FROM project-builder

ARG USER=dev-user
ARG PASSWORD=password
ARG PKG_LIST="epel-release passwd openssh-server dnsutils telnet net-tools iproute zsh java-17-openjdk-devel vim procps gvim gedit ibus ibus-libzhuyin mesa-libGLU xfce-polkit"
ARG JAVA_OPTS="-Dfile.encoding=UTF-8"

# 安裝必要套件
RUN sudo dnf install -yq $PKG_LIST && sudo dnf clean all
# 設定使用者密碼
RUN echo -e "$PASSWORD\n$PASSWORD\n" | sudo passwd $USER
# 設定wsl.conf
RUN echo -e "[boot]\nsystemd = true\ncommand = ibus-daemon --xim" | sudo tee -a /etc/wsl.conf && \
    echo -e "[user]\ndefault = $USER" | sudo tee -a /etc/wsl.conf && \ 
    echo '#!/usr/bin/bash' | sudo tee -a /usr/bin/open && \
    echo -e "\
    ARG=\"./\"\n\
    [[ \$@ != \"\" ]] && ARG=\$@\n\
    powershell.exe ii \$ARG\n\
    " | sudo tee -a /usr/bin/open && \
    sudo chmod +x /usr/bin/open || \
    exit 0
# 設定通用開發環境，因配合WSL所以Dockerfile的ENV不能用
RUN echo -e "\n\
export MAVEN_CONFIG=\"/home/$USER/.m2\"\n\
export JAVA_TOOL_OPTIONS=\"$JAVA_OPTS\"\n\
export THROWERROR=\"true\"\n\
export TZ=\"Asia/Taipei\"\n\
export JAVA_HOME=\"/opt/jdk\"\n\
export PATH=\"\$JAVA_HOME/bin:/opt/mvn/bin:\$PATH\"\n\
export LANG=\"zh_TW.UTF-8\"\n\
export LC_ALL=\"C.UTF-8\"\n\n\
export GTK_IM_MODULE=ibus\n\
export XMODIFIERS=@im=ibus\n\
export QT_IM_MODULE=ibus\n\n\
bash ~/.sysinit\n\
sudo chown -R \$(whoami):\$(whoami) /run/user/\$(id -u)/\n\n\
[ -z "$( ps ux | grep ibus-daemon | grep -v grep)" ] && dbus-launch ibus-daemon -drx\n\n\ 
alias code=\"code --remote wsl+\$WSL_DISTRO_NAME\"\
" | tee -a /home/$USER/.userrc
RUN echo "source ~/.userrc" | tee -a ~/.bashrc
# 複製使用者的systemd啟動script
COPY .sysinit /home/$USER/
