FROM project-builder

ARG USER=dev-user
ARG PASSWORD=password
ARG PKG_LIST="epel-release netcat tmux passwd unzip openssh-server dnsutils telnet net-tools iproute zsh java-17-openjdk-devel vim procps gvim gedit fcitx fcitx-chewing libglvnd-glx dbus-x11  mesa-libGLU-devel man-pages"
ARG JAVA_OPTS="-Dfile.encoding=UTF-8"

# 安裝必要套件
RUN sudo dnf install -yq $PKG_LIST && sudo dnf clean all
# 設定使用者密碼
RUN echo -e "$PASSWORD\n$PASSWORD\n" | sudo passwd $USER
# 設定wsl.conf
RUN echo -e "[boot]\nsystemd = true" | sudo tee -a /etc/wsl.conf && \
    echo -e "[user]\ndefault = $USER" | sudo tee -a /etc/wsl.conf 
# 下載中文字體
RUN mkdir -p ~/.fonts && \
    wget -P ~/.fonts -O ~/.fonts/NotoSansTC.zip https://fonts.google.com/download?family=Noto%20Sans%20TC && \
    unzip -d ~/.fonts ~/.fonts/NotoSansTC.zip
# 設定通用開發環境，因配合WSL所以Dockerfile的ENV不能用
RUN echo -e "\n\
export MAVEN_CONFIG=\"/home/$USER/.m2\"\n\
export JAVA_TOOL_OPTIONS=\"$JAVA_OPTS\"\n\
export THROWERROR=\"true\"\n\
export TZ=\"Asia/Taipei\"\n\
export JAVA_HOME=\"/opt/jdk\"\n\
export PATH=\"\$JAVA_HOME/bin:/opt/mvn/bin:\$PATH\"\n\
export LANG=\"zh_TW.UTF-8\"\n\
export LC_ALL=\"zh_TW.UTF-8\"\n\n\
export GTK_IM_MODULE=fcitx\n\
export XMODIFIERS=@im=fcitx\n\
export QT_IM_MODULE=fcitx\n\n\
eval \$(dbus-launch --sh-syntax)\n\
if [[ -z \"\$TMUX\" ]] && [[ -z \"\$VSCODE_INJECTION\" ]]\nthen\n\
    tmux attach-session -t \$USER || tmux new-session -s \$USER\n\
fi\n\
if [[ -n \"\$TMUX\" ]]\nthen\n\ 
    dbus-launch fcitx -dr &>/dev/null\n\
fi\n\
" | tee -a /home/$USER/.userrc
RUN echo "source ~/.userrc" | tee -a ~/.bashrc | tee -a ~/.zshrc
RUN tmux new -s $USER -d
